/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BDLogica.LogCliente;
import BDLogica.LogFactura;
import BDLogica.LogPedido;
import BDLogica.LogPlato;
import BDLogica.LogPlatopedido;
import Entidades.Cliente;
import Entidades.Factura;
import Entidades.Pedido;
import Entidades.Plato;
import Entidades.Platopedido;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class CierreCaja extends javax.swing.JInternalFrame {
    
    
     List<Factura> arrayfactura = new ArrayList<Factura>();
    List<Pedido> arraypedido = new ArrayList<Pedido>();
    List<Platopedido> arrayplatopedido = new ArrayList<Platopedido>();
    List<Plato> arrayplato = new ArrayList<Plato>();
    List<Cliente> arraycliente = new ArrayList<Cliente>();
    static LogCliente objLogCliente = new LogCliente();
    static LogPedido objLogPedido = new LogPedido();
    static LogPlato objLogPlato = new LogPlato();
     static LogFactura objLogFactura = new LogFactura();
      static LogPlatopedido objLogPlatoPedido = new LogPlatopedido();
      int direccion = -1;
    /**
     * Creates new form CierreCaja
     */
    public CierreCaja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFact1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableFact2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButtonGenerar = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setClosable(true);
        setMaximizable(true);

        jTableFact1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableFact1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFact1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFact1);

        jLabel1.setText("FACTURAS");

        jLabel2.setText("Total:");

        jTextField1.setText("jTextField1");

        jTableFact2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableFact2);

        jLabel3.setText("Descripcion Factura");

        jButtonGenerar.setText("Generar");
        jButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonGenerar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(272, 272, 272))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGenerar))
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarActionPerformed
        // TODO add your handling code here:
         double v=0;
        arrayfactura.clear();
        arrayfactura = objLogFactura.findFacturaEntities();
        jTableFact1.removeAll();
        Object valor[]={"Num.Fac","Fecha","Valor"};
        DefaultTableModel modelo = new DefaultTableModel(null,valor);
        jTableFact1.setModel(modelo);
        
        for (int i = 0; i < arrayfactura.size(); i++) {
            String d[]={arrayfactura.get(i).getNumeroFactura(),arrayfactura.get(i).getFecha(),String.valueOf(arrayfactura.get(i).getValor())};
            modelo.addRow(d);
            
            v+=arrayfactura.get(i).getValor();
        }
        jTextField1.setText(String.valueOf(v));
    }//GEN-LAST:event_jButtonGenerarActionPerformed

    private void jTableFact1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFact1MouseClicked
        // TODO add your handling code here:
        
        direccion =  jTableFact1.getSelectedRow();
        Listar(arrayfactura.get(direccion));
        
    }//GEN-LAST:event_jTableFact1MouseClicked
public void Listar(Factura dato){
        Pedido p = new Pedido();
        List<Plato> pl = new ArrayList<Plato>();
        Platopedido pp = new Platopedido();
        Cliente c = new Cliente();
        arraycliente = objLogCliente.findClienteEntities();
        arraypedido = objLogPedido.findPedidoEntities();
        arrayplato = objLogPlato.findPlatoEntities();
        arrayplatopedido= objLogPlatoPedido.findPlatopedidoEntities();
        for (int i = 0; i < arraypedido.size(); i++) {
            if(arraypedido.get(i).getIdPedido()== dato.getIdPedido().getIdPedido()){
                p = arraypedido.get(i);
            }
        }
        for (int i = 0; i < arrayplatopedido.size(); i++) {
            if(arrayplatopedido.get(i).getIdPedido().getIdPedido()==p.getIdPedido()){
                pl.add(arrayplatopedido.get(i).getIdPlato());
            }
        }
        for (int i = 0; i < arraycliente.size(); i++) {
            if(arraycliente.get(i).getIdCliente()== dato.getIdCliente().getIdCliente()){
            c = arraycliente.get(i);
            
            }
        }
        jTableFact2.removeAll();
        Object arreglo[]={"Nombre","Descripcion","Valor","Cliente","Num Mesa"};
        DefaultTableModel model = new DefaultTableModel(null,arreglo);
        jTableFact2.setModel(model);
        for (int i = 0; i < pl.size(); i++) {
            String valores []= {pl.get(i).getNombre(),pl.get(i).getDescripcion(),String.valueOf(pl.get(i).getCosto()),c.getNombre(),String.valueOf(p.getNumMesa())};
            model.addRow(valores);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableFact1;
    private javax.swing.JTable jTableFact2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
