/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.Cliente;
import Entidades.Factura;
import Entidades.Pedido;
import Entidades.Plato;
import BDLogica.LogCliente;
import BDLogica.LogFactura;
import BDLogica.LogFeedback;
import BDLogica.LogMenu;
import BDLogica.LogPedido;
import BDLogica.LogPlato;
import BDLogica.LogPlatopedido;
import BDLogica.exceptions.NonexistentEntityException;
import CLases.PlatoPedido;
import Entidades.Feedback;
import Entidades.Platopedido;
//import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author antse
 */
public class FacturaPantalla extends javax.swing.JInternalFrame {

    /**
     * Creates new form Factura
     */
    static Pedido objNumeroPedido = new Pedido();
    static LogPedido objLogPedido = new LogPedido();
    static LogPlato objLogPlato = new LogPlato();
    static Pedido objPedido = new Pedido();
    static Pedido objPedidoAux = new Pedido();
    static LogMenu objLogMenu = new LogMenu();
    static LogFactura objLogFactura = new LogFactura();
    static LogCliente objLogCliente = new LogCliente();
    static LogPlatopedido objLogPlatoPedido = new LogPlatopedido();
    static LogFeedback objLogFeedback = new LogFeedback();
    static Cliente objCliente = new Cliente();
    static Factura objFactura = new Factura();
    static List<Factura> ArrayFactura = new ArrayList<Factura>();
    static List<Pedido> ArrayPedido = new ArrayList<Pedido>();
    static List<Plato> ArrayPlato = new ArrayList<Plato>();
    static List<Cliente> ArrayCliente = new ArrayList<Cliente>();
    static List<Pedido> PedidosListos = new ArrayList<Pedido>();

    java.sql.Date sqlDate = new java.sql.Date(System.currentTimeMillis());

    int rowSel = -1;

    public FacturaPantalla() {
        initComponents();

        ArrayPedido = objLogPedido.findPedidoEntities();
        ListarPedidos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCalificacion = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedidos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDescripcionPedido = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNroPedido = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextTotalPagar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonCrearFactura = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldNroFactura = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jRadio1Estrella = new javax.swing.JRadioButton();
        jRadio3Estrella = new javax.swing.JRadioButton();
        jRadio5Estrella = new javax.swing.JRadioButton();
        jRadio4Estrella = new javax.swing.JRadioButton();
        jRadio2Estrella = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jButtonCrear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNombreApellido1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePedidos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 433, 103));

        jTableDescripcionPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableDescripcionPedido);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 433, 104));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("FACTURACION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jTextFieldNroPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNroPedidoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNroPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 114, -1));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel3.setText("Informacion factura");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        jLabel8.setText("Total a pagar:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jTextTotalPagar.setEnabled(false);
        jTextTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTotalPagarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 186, -1));

        jLabel11.setText("Pedidos");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, 14));

        jLabel12.setText("Descripcion del pedido");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, 14));

        jButtonCrearFactura.setText("Crear Factura");
        jButtonCrearFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCrearFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 670, -1, -1));

        jLabel13.setText("Nro. Factura:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        jLabel14.setText("Fecha:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        jTextFieldNroFactura.setEnabled(false);
        getContentPane().add(jTextFieldNroFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 188, -1));

        jTextFieldFecha.setEnabled(false);
        getContentPane().add(jTextFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 188, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 358, -1));

        jLabel15.setText("Feedback:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel16.setText("Calificacion:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        buttonGroupCalificacion.add(jRadio1Estrella);
        jRadio1Estrella.setText("1 Estrellas");
        jRadio1Estrella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio1EstrellaActionPerformed(evt);
            }
        });
        jPanel1.add(jRadio1Estrella, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        buttonGroupCalificacion.add(jRadio3Estrella);
        jRadio3Estrella.setText("3 Estrellas");
        jPanel1.add(jRadio3Estrella, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        buttonGroupCalificacion.add(jRadio5Estrella);
        jRadio5Estrella.setText("5 Estrellas");
        jPanel1.add(jRadio5Estrella, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        buttonGroupCalificacion.add(jRadio4Estrella);
        jRadio4Estrella.setText("4 Estrelllas");
        jPanel1.add(jRadio4Estrella, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        buttonGroupCalificacion.add(jRadio2Estrella);
        jRadio2Estrella.setText("2 Estrellas");
        jPanel1.add(jRadio2Estrella, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 930, 140));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 188, -1));

        jLabel6.setText("Direccion:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel7.setText("Nombres ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 20));
        jPanel2.add(jTextFieldCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 188, -1));

        jLabel4.setText("Apellidos");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 20));
        jPanel2.add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 188, -1));

        jButtonCrear.setText("BuscarCliente");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jLabel2.setText("C.I.:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));
        jPanel2.add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 188, -1));

        jLabel5.setText("Telefono/Celular:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jTextFieldNombreApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreApellido1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldNombreApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 188, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 480, 240));

        jButton1.setText("Actualizar Pedidos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadio1EstrellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio1EstrellaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio1EstrellaActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            // TODO add your handling code here:

            BuscarPedido();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(FacturaPantalla.class.getName()).log(Level.SEVERE, null, ex);
        }

//        try {
//            ListarPlatos();
//        } catch (IOException | ClassNotFoundException ex) {
//            Logger.getLogger(FacturaPantalla.class.getName()).log(Level.SEVERE, null, ex);
//        }
        try {
            GenerarNumeroFactura();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(FacturaPantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed
    public void GenerarNumeroFactura() throws IOException, FileNotFoundException, ClassNotFoundException {
        int numeroFactura;
        ArrayFactura = objLogFactura.findFacturaEntities();
        numeroFactura = ArrayFactura.size();
        if (numeroFactura == 0) {
            objFactura.setIdFactura(1);
            this.jTextFieldNroFactura.setText(String.valueOf(1));
            this.jTextFieldFecha.setText(String.valueOf(sqlDate));
        } else {
            numeroFactura = ArrayFactura.get(ArrayFactura.size() - 1).getIdFactura() + 1;
            this.jTextFieldNroFactura.setText(String.valueOf(numeroFactura));
            this.jTextFieldFecha.setText(String.valueOf(sqlDate));
            objFactura.setIdFactura(numeroFactura);
        }
    }
    private void jTextFieldNroPedidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNroPedidoKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldNroPedidoKeyTyped

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        // TODO add your handling code here:
        if (this.jButtonCrear.getText().equals("BuscarCliente")) {
//            objCliente.setCedula(this.jTextFieldCI.getText());
//            ArrayCliente = objLogCliente.findClienteEntities();
            System.out.println("///////");
            try {
                if (VerificarCliente()) {
                    this.jTextFieldNombreApellido1.setText(objCliente.getNombre());
                    this.jTextFieldApellido.setText(objCliente.getApellido());
                    this.jTextFieldTelefono.setText(objCliente.getCelular());
                    this.jTextFieldDireccion.setText(objCliente.getDireccion());
                    this.jTextFieldNombreApellido1.setEnabled(false);
                    this.jTextFieldApellido.setEnabled(false);
                    this.jTextFieldTelefono.setEnabled(false);
                    this.jTextFieldDireccion.setEnabled(false);
                    JOptionPane.showMessageDialog(null, "Cliente Encontrado");
                } else {
                    this.jButtonCrear.setText("Crear");
                    JOptionPane.showMessageDialog(null, "No se encontro el cliente");
                    jTextFieldNombreApellido1.setText("");
                    jTextFieldApellido.setText("");
                    jTextFieldTelefono.setText("");
                    jTextFieldDireccion.setText("");
                    this.jTextFieldNombreApellido1.setEnabled(true);
                    this.jTextFieldApellido.setEnabled(true);
                    this.jTextFieldTelefono.setEnabled(true);
                    this.jTextFieldDireccion.setEnabled(true);

                }

            } catch (IOException ex) {
                Logger.getLogger(FacturaPantalla.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FacturaPantalla.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        if (jButtonCrear.getText().equals("Crear")) {

            if (jTextFieldCI.getText().equals("") || jTextFieldNombreApellido1.getText().equals("") || jTextFieldApellido.getText().equals("") || jTextFieldTelefono.getText().equals("") || jTextFieldDireccion.getText().equals("")) {

                JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
            } else {
                objCliente.setCedula(jTextFieldCI.getText());
                objCliente.setNombre(jTextFieldNombreApellido1.getText());
                objCliente.setApellido(jTextFieldApellido.getText());
                objCliente.setCelular(jTextFieldTelefono.getText());
                objCliente.setDireccion(jTextFieldDireccion.getText());

                objLogCliente.create(objCliente);
                JOptionPane.showMessageDialog(null, "Cliente creado");
                jButtonCrear.setEnabled(false);
                this.jTextFieldCI.setEnabled(false);
                this.jTextFieldNombreApellido1.setEnabled(false);
                this.jTextFieldApellido.setEnabled(false);
                this.jTextFieldTelefono.setEnabled(false);
                this.jTextFieldDireccion.setEnabled(false);
            }

        }


    }//GEN-LAST:event_jButtonCrearActionPerformed

    public boolean VerificarCliente() throws IOException, FileNotFoundException, ClassNotFoundException {
        String cedulaCliente = jTextFieldCI.getText();

        ArrayCliente = objLogCliente.findClienteEntities();
        System.out.println(ArrayCliente);
        for (Cliente aux : ArrayCliente) {
            System.out.println(aux.getCedula());
            System.out.println(cedulaCliente);
            if (aux.getCedula().trim().equals(cedulaCliente.trim())) {
                objCliente = aux;
                System.out.println(objCliente);
                return true;
            }

        }
        return false;

    }

    private void jButtonCrearFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearFacturaActionPerformed
        // TODO add your handling code here:
        String dato = "";
        if (jTextArea1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe llenar la observacion");
        } else {
            if (jRadio1Estrella.isSelected()) {
                dato = jRadio1Estrella.getText();
            }
            if (jRadio2Estrella.isSelected()) {
                dato = jRadio2Estrella.getText();
            }
            if (jRadio3Estrella.isSelected()) {
                dato = jRadio3Estrella.getText();
            }
            if (jRadio4Estrella.isSelected()) {
                dato = jRadio4Estrella.getText();
            }
            if (jRadio5Estrella.isSelected()) {
                dato = jRadio5Estrella.getText();
            }
            Feedback f = new Feedback();
            f.setCalificacion(dato);
            f.setObservacion(jTextArea1.getText());
            objLogFeedback.create(f);
        }
        System.out.println("Se va a crear la factura");
        Cliente cl = BuscarCliente();
        objFactura.setIdCliente(cl);
        Feedback fe = BuscarFeedBack();
        objFactura.setIdFeedBack(fe);

        objFactura.setIdPedido(objNumeroPedido);
        objFactura.setValor(Double.parseDouble(jTextTotalPagar.getText()));
        objFactura.setNumeroFactura(jTextFieldNroFactura.getText());
        objFactura.setFecha(String.valueOf(sqlDate));

        objLogFactura.create(objFactura);
        JOptionPane.showMessageDialog(this, "Factura Creada");
        this.jTextFieldCI.setText("");
        this.jTextFieldNombreApellido1.setText("");
        this.jTextFieldApellido.setText("");
        this.jTextFieldTelefono.setText("");
        this.jTextFieldDireccion.setText("");
        this.jTextArea1.setText("");
        objPedido = objLogPedido.findPedido(objNumeroPedido.getIdPedido());
        objPedido.setEstado(4);
        try {
            objLogPedido.edit(objPedido);
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(FacturaPantalla.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FacturaPantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
        ListarPedidos();

    }//GEN-LAST:event_jButtonCrearFacturaActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTablePedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePedidosMouseClicked
        rowSel = jTablePedidos.getSelectedRow();
        System.out.println(rowSel);
        objNumeroPedido = PedidosListos.get(rowSel);
        try {
            ListarPlatos();
        } catch (IOException ex) {
            Logger.getLogger(FacturaPantalla.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FacturaPantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTablePedidosMouseClicked

    private void jTextFieldNombreApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreApellido1ActionPerformed

    private void jTextTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTotalPagarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ListarPedidos();
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public void BuscarPedido() throws IOException, FileNotFoundException, ClassNotFoundException {
        int busquedaPedido = Integer.parseInt(jTextFieldNroPedido.getText());
        objNumeroPedido.setNumeroPedido(busquedaPedido);
        ArrayPedido = objLogPedido.findPedidoEntities();
        boolean bandera = false;
        for (Pedido aux : ArrayPedido) {
            if (aux.getNumeroPedido() == busquedaPedido && aux.getEstado() == 3) {
                objNumeroPedido = aux;
                bandera = true;
            }
        }
        if (bandera) {
            ListarPlatos();
        } else {
            JOptionPane.showMessageDialog(this, "Lo sentimos el pedido no esta disponible para facturacion");
        }

    }

    public void ListarPlatos() throws IOException, FileNotFoundException, ClassNotFoundException {

        List<Platopedido> ArrayPlatoPedido = new ArrayList<Platopedido>();
        double dato = 0;
//        objLogPlato.LeerPlatos(ArrayPlatos);
//        ArrayPlatos = objLogMenu.MenuActivo().getListaPlatosMenu();
        ArrayPlatoPedido = objLogPlatoPedido.findPlatopedidoEntities();
        jTableDescripcionPedido.removeAll();
        Object columnas[] = {"Nombre", "Descripcion", "Coste", "Cantidad"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTableDescripcionPedido.setModel(modelo);
        for (Platopedido objaux : ArrayPlatoPedido) {
            if (objaux.getIdPedido().getIdPedido() == objNumeroPedido.getIdPedido()) {
                String NewValor[] = {
                    objaux.getIdPlato().getNombre(),
                    objaux.getIdPlato().getDescripcion(),
                    String.valueOf(objaux.getIdPlato().getCosto()),
                    String.valueOf(objaux.getCantidad())

                };
                modelo.addRow(NewValor);
                dato += objaux.getIdPlato().getCosto() * objaux.getCantidad();

            }

        }
        jTextTotalPagar.setText(String.valueOf(dato));
    }

    public Cliente BuscarCliente() {
        List<Cliente> arraycliente = new ArrayList<Cliente>();
        arraycliente = objLogCliente.findClienteEntities();
        for (Cliente c : arraycliente) {
            if (c.getCedula().equals(objCliente.getCedula())) {
                return c;
            }
        }

        return null;

    }

    public Feedback BuscarFeedBack() {

        int aux;
        List<Feedback> arrayfeedback = new ArrayList<Feedback>();
        arrayfeedback = objLogFeedback.findFeedbackEntities();
        aux = arrayfeedback.size();
        if (aux == 0) {
            JOptionPane.showMessageDialog(null, "No hay feedbacks");

        }

        return arrayfeedback.get(arrayfeedback.size() - 1);

    }

    void ListarPedidos() {
        jTablePedidos.removeAll();
        ArrayPedido = objLogPedido.findPedidoEntities();
        Object columnas[] = {"Numero de Orden", "Numero Mesa"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTablePedidos.setModel(modelo);
        for (Pedido objNumeroPedido : ArrayPedido) {
            if (objNumeroPedido.getEstado() == 3) {
                PedidosListos.add(objNumeroPedido);
                String NewValor[] = {
                    String.valueOf(objNumeroPedido.getNumeroPedido()),
                    String.valueOf(objNumeroPedido.getNumMesa())
                };
                modelo.addRow(NewValor);
            }
        }
    }

//    public void ListarPedidos() throws IOException, FileNotFoundException, ClassNotFoundException {
//
//        ArrayPedidos.removeAll(ArrayPedidos);
//        objLogPedido.LeerPedido(ArrayPedidos);
//        //ArrayPlatos = objLogMenu.MenuActivo().getListaPlatosMenu();
//
//        jTablePedidos.removeAll();
//        Object columnas[] = {"Numero de Orden", "Numero de Mesa"};
//        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
//        jTablePedidos.setModel(modelo);
//        for (Pedido objAux : ArrayPedidos) {
//            String NewValor[] = {
//                String.valueOf(objAux.getNumeroPedido()),
//                String.valueOf(objAux.getNumeroMesa())
//            };
//            modelo.addRow(NewValor);
//        }
//
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCalificacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonCrearFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadio1Estrella;
    private javax.swing.JRadioButton jRadio2Estrella;
    private javax.swing.JRadioButton jRadio3Estrella;
    private javax.swing.JRadioButton jRadio4Estrella;
    private javax.swing.JRadioButton jRadio5Estrella;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableDescripcionPedido;
    private javax.swing.JTable jTablePedidos;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCI;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldNombreApellido1;
    private javax.swing.JTextField jTextFieldNroFactura;
    private javax.swing.JTextField jTextFieldNroPedido;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextTotalPagar;
    // End of variables declaration//GEN-END:variables
}
