/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.Cajero;
import Entidades.Cocinero;
//import CLases.Empleado;
import Entidades.Mesero;

import BDLogica.LogCajero;
import BDLogica.LogCocinero;
//import Logica.LogEmpleado;
import BDLogica.LogMesero;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class RegistrarEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrarPersonal
     */
    Cocinero objCocinero = new Cocinero();
    Cajero objCajero = new Cajero();
    Mesero objMesero = new Mesero();

    //LogEmpleado objLogEmpleado = new LogEmpleado();
    LogCocinero objLogCocinero = new LogCocinero();
    LogMesero objLogMesero = new LogMesero();
    LogCajero objLogCajero = new LogCajero();

    //List<Empleado> ArrayEmpleados;
    List<Cocinero> ArrayCocineros;
    List<Mesero> ArrayMeseros;
    List<Cajero> ArrayCajeros;

    public RegistrarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonListarEmpleados = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxRol = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldHorario = new javax.swing.JTextField();
        jSpinnerSueldo = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jButtonCrearEmpleado = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCelular = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Direccion", "Celular", "Rol", "Codigo", "Horario", "Sueldo"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpleados);

        jLabel1.setText("Lista de Empleados");

        jButtonListarEmpleados.setText("Listar Empleados");
        jButtonListarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarEmpleadosActionPerformed(evt);
            }
        });

        jLabel2.setText("Cedula");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("Direccion");

        jLabel6.setText("Rol");

        jComboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un rol...", "Mesero", "Cocinero", "Cajero" }));
        jComboBoxRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRolActionPerformed(evt);
            }
        });

        jLabel7.setText("Codigo");

        jLabel8.setText("Horario");

        jLabel9.setText("Sueldo");

        jSpinnerSueldo.setModel(new javax.swing.SpinnerNumberModel(400.0d, null, null, 0.10000000149011612d));

        jLabel10.setText("Dolares");

        jButtonCrearEmpleado.setText("Crear Empleado");
        jButtonCrearEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearEmpleadoActionPerformed(evt);
            }
        });

        jLabel11.setText("Celular");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonListarEmpleados))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
                            .addComponent(jSeparator1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNombre)
                                    .addComponent(jTextFieldCedula)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(30, 30, 30)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCelular))))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldCodigo)
                                    .addComponent(jComboBoxRol, 0, 150, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addComponent(jLabel10)))
                        .addGap(91, 91, 91)
                        .addComponent(jButtonCrearEmpleado)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarEmpleados)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButtonCrearEmpleado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jSpinnerSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarEmpleadosActionPerformed

        try {
            leerEmpleados();
        } catch (IOException ex) {
            Logger.getLogger(RegistrarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.jTableEmpleados.removeAll();
        Object columnas[] = {"Cedula", "Nombre", "Apellido", "Direccion", "Celular", "Rol", "Codigo", "horario", "Sueldo"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTableEmpleados.setModel(modelo);
        for (Object objAux : ArrayCocineros) {
            Cocinero objEmpleado = (Cocinero) objAux;

            String NewValor[] = {
                objEmpleado.getCedula(),
                objEmpleado.getNombre(),
                objEmpleado.getApellido(),
                objEmpleado.getDireccion(),
                objEmpleado.getCelular(),
                "cocinero",
                objEmpleado.getCodigo(),
                objEmpleado.getHorario(),
                String.valueOf(objEmpleado.getSueldo())
            };
            modelo.addRow(NewValor);
        }
        for (Object objAux : ArrayMeseros) {
            Mesero objEmpleado = (Mesero) objAux;

            String NewValor[] = {
                objEmpleado.getCedula(),
                objEmpleado.getNombre(),
                objEmpleado.getApellido(),
                objEmpleado.getDireccion(),
                objEmpleado.getCelular(),
                "mesero",
                objEmpleado.getCodigo(),
                objEmpleado.getHorario(),
                String.valueOf(objEmpleado.getSueldo())
            };
            modelo.addRow(NewValor);
        }
        for (Object objAux : ArrayCajeros) {
            Cajero objEmpleado = (Cajero) objAux;
//                if (this.jComboBoxRol.getSelectedItem().toString().equals("cocinero")) {
//                    rol = "cocinero";
//                }
            String NewValor[] = {
                objEmpleado.getCedula(),
                objEmpleado.getNombre(),
                objEmpleado.getApellido(),
                objEmpleado.getDireccion(),
                objEmpleado.getCelular(),
                "cajero",
                objEmpleado.getCodigo(),
                objEmpleado.getHorario(),
                String.valueOf(objEmpleado.getSueldo())
            };
            modelo.addRow(NewValor);
        }

    }//GEN-LAST:event_jButtonListarEmpleadosActionPerformed

    private void jButtonCrearEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearEmpleadoActionPerformed
        Double sueldo = (Double) this.jSpinnerSueldo.getValue();
        if (this.jComboBoxRol.getSelectedItem().toString().equals("Cocinero")) {

            Cocinero objCocineroAux = new Cocinero();
            objCocineroAux.setApellido(this.jTextFieldApellido.getText());
            objCocineroAux.setCedula(this.jTextFieldCedula.getText());
            objCocineroAux.setCelular(this.jTextFieldCelular.getText());
            objCocineroAux.setCodigo(this.jTextFieldCodigo.getText());
            objCocineroAux.setDireccion(this.jTextFieldDireccion.getText());
            objCocineroAux.setHorario(this.jTextFieldHorario.getText());
            objCocineroAux.setSueldo(sueldo);
            objCocineroAux.setNombre(this.jTextFieldNombre.getText());

            objLogCocinero.create(objCocineroAux);
        }
        if (this.jComboBoxRol.getSelectedItem().toString().equals("Mesero")) {

            Mesero objMeseroAux = new Mesero();
            objMeseroAux.setApellido(this.jTextFieldApellido.getText());
            objMeseroAux.setCedula(this.jTextFieldCedula.getText());
            objMeseroAux.setCelular(this.jTextFieldCelular.getText());
            objMeseroAux.setCodigo(this.jTextFieldCodigo.getText());
            objMeseroAux.setDireccion(this.jTextFieldDireccion.getText());
            objMeseroAux.setHorario(this.jTextFieldHorario.getText());
            objMeseroAux.setSueldo(sueldo);
            objMeseroAux.setNombre(this.jTextFieldNombre.getText());
            
            
            
            objLogMesero.create(objMeseroAux);
        }
        if (this.jComboBoxRol.getSelectedItem().toString().equals("Cajero")) {
            
            Cajero objCajeroAux = new Cajero();
            objCajeroAux.setApellido(this.jTextFieldApellido.getText());
            objCajeroAux.setCedula(this.jTextFieldCedula.getText());
            objCajeroAux.setCelular(this.jTextFieldCelular.getText());
            objCajeroAux.setCodigo(this.jTextFieldCodigo.getText());
            objCajeroAux.setDireccion(this.jTextFieldDireccion.getText());
            objCajeroAux.setHorario(this.jTextFieldHorario.getText());
            objCajeroAux.setSueldo(sueldo);
            objCajeroAux.setNombre(this.jTextFieldNombre.getText());
            
            objLogCajero.create(objCajeroAux);
        }
        JOptionPane.showMessageDialog(this, "Empleado Creado");
        this.jButtonListarEmpleadosActionPerformed(evt);
        this.jTextFieldCedula.setText("");
        this.jTextFieldNombre.setText("");
        this.jTextFieldApellido.setText("");
        this.jTextFieldCedula.setText("");
        this.jTextFieldCelular.setText("");
        this.jTextFieldDireccion.setText("");
        this.jTextFieldHorario.setText("");
    }//GEN-LAST:event_jButtonCrearEmpleadoActionPerformed

    private void jComboBoxRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRolActionPerformed

    void leerEmpleados() throws IOException, FileNotFoundException, ClassNotFoundException {

        ArrayCocineros = objLogCocinero.findCocineroEntities();
        ArrayMeseros = objLogMesero.findMeseroEntities();
        ArrayCajeros = objLogCajero.findCajeroEntities();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearEmpleado;
    private javax.swing.JButton jButtonListarEmpleados;
    private javax.swing.JComboBox<String> jComboBoxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerSueldo;
    private javax.swing.JTable jTableEmpleados;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldHorario;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
