/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.Menu;
import Entidades.Plato;
import BDLogica.LogMenu;
import BDLogica.LogPlato;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class AdministrarMenus extends javax.swing.JInternalFrame {

    LogPlato objLogPlato = new LogPlato();
    List ArrayPlatos;

    LogMenu objLogMenu = new LogMenu();
    List ArrayMenu;

    int rowSelPlato = -1;
    int rowSelMenu = -1;
    int rowSelPlatoMenu = -1;

    /**
     * Creates new form AdministrarMenus
     */
    public AdministrarMenus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaMenus = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePlatosMenu = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableListaPlatos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jRadioButtonLunes = new javax.swing.JRadioButton();
        jRadioButtonMartes = new javax.swing.JRadioButton();
        jRadioButtonMiercoles = new javax.swing.JRadioButton();
        jRadioButtonJueves = new javax.swing.JRadioButton();
        jRadioButtonViernes = new javax.swing.JRadioButton();
        jRadioButtonSabado = new javax.swing.JRadioButton();
        jRadioButtonDomingo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonEnero = new javax.swing.JRadioButton();
        jRadioButtonFebrero = new javax.swing.JRadioButton();
        jRadioButtonMarzo = new javax.swing.JRadioButton();
        jRadioButtonAbril = new javax.swing.JRadioButton();
        jRadioButtonMayo = new javax.swing.JRadioButton();
        jRadioButtonJunio = new javax.swing.JRadioButton();
        jRadioButtonSeptiembre = new javax.swing.JRadioButton();
        jRadioButtonOctubre = new javax.swing.JRadioButton();
        jRadioButtonNoviembre = new javax.swing.JRadioButton();
        jRadioButtonDiciembre = new javax.swing.JRadioButton();
        jRadioButtonJulio = new javax.swing.JRadioButton();
        jRadioButtonAgosto = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonCrearMenu = new javax.swing.JButton();
        jButtonListarMenus = new javax.swing.JButton();
        jButtonListarPlatos = new javax.swing.JButton();
        jButtonAgregarMenu = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jTableListaMenus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Dias", "Meses"
            }
        ));
        jTableListaMenus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaMenusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaMenus);

        jTablePlatosMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Costo", "Descripcion", "Tiempo Aprox."
            }
        ));
        jScrollPane2.setViewportView(jTablePlatosMenu);

        jTableListaPlatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Costo", "Descripcion", "Tiempo Aprox."
            }
        ));
        jScrollPane3.setViewportView(jTableListaPlatos);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setText("Registrar un Nuevo Menu");

        jLabel2.setText("Nombre del Menu");

        jLabel3.setText("Descripcion");

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setRows(5);
        jScrollPane4.setViewportView(jTextAreaDescripcion);

        jRadioButtonLunes.setText("Lunes");
        jRadioButtonLunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLunesActionPerformed(evt);
            }
        });

        jRadioButtonMartes.setText("Martes");
        jRadioButtonMartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMartesActionPerformed(evt);
            }
        });

        jRadioButtonMiercoles.setText("Miercoles");

        jRadioButtonJueves.setText("Jueves");

        jRadioButtonViernes.setText("Viernes");

        jRadioButtonSabado.setText("Sabado");

        jRadioButtonDomingo.setText("Domingo");

        jLabel4.setText("Dias");

        jLabel5.setText("Seleccione los dias de la semana que estara disponible el menu");

        jLabel6.setText("Seleccione los meses en que estara disponible el menu");

        jRadioButtonEnero.setText("Enero");

        jRadioButtonFebrero.setText("Febrero");

        jRadioButtonMarzo.setText("Marzo");

        jRadioButtonAbril.setText("Abril");

        jRadioButtonMayo.setText("Mayo");

        jRadioButtonJunio.setText("Junio");

        jRadioButtonSeptiembre.setText("Septiembre");

        jRadioButtonOctubre.setText("Octubre");

        jRadioButtonNoviembre.setText("Noviembre");

        jRadioButtonDiciembre.setText("Diciembre");

        jRadioButtonJulio.setText("Julio");

        jRadioButtonAgosto.setText("Agosto");

        jLabel7.setText("Meses");

        jButtonCrearMenu.setText("Crear Menu");
        jButtonCrearMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonLunes)
                            .addComponent(jRadioButtonMiercoles)
                            .addComponent(jRadioButtonViernes)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonMartes)
                                    .addComponent(jRadioButtonJueves))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonDomingo)
                                    .addComponent(jRadioButtonSabado)))
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonEnero)
                                    .addComponent(jRadioButtonFebrero)
                                    .addComponent(jRadioButtonMarzo)
                                    .addComponent(jRadioButtonAbril)
                                    .addComponent(jRadioButtonMayo)
                                    .addComponent(jRadioButtonJunio))
                                .addGap(77, 77, 77)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonJulio)
                                    .addComponent(jRadioButtonAgosto)
                                    .addComponent(jRadioButtonSeptiembre)
                                    .addComponent(jRadioButtonOctubre)
                                    .addComponent(jRadioButtonNoviembre)
                                    .addComponent(jRadioButtonDiciembre)))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldNombre)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCrearMenu)
                        .addGap(37, 37, 37))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(jRadioButtonLunes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMartes)
                    .addComponent(jRadioButtonSabado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMiercoles)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonJueves)
                    .addComponent(jRadioButtonDomingo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonViernes)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonEnero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonFebrero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonMarzo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonAbril)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonMayo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonJunio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonJulio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonAgosto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonSeptiembre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonOctubre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonNoviembre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDiciembre)))
                .addGap(18, 18, 18)
                .addComponent(jButtonCrearMenu)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jButtonListarMenus.setText("Listar Menus");
        jButtonListarMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarMenusActionPerformed(evt);
            }
        });

        jButtonListarPlatos.setText("Listar Platos");
        jButtonListarPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarPlatosActionPerformed(evt);
            }
        });

        jButtonAgregarMenu.setText("Agregar al menu seleccionado");
        jButtonAgregarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarMenuActionPerformed(evt);
            }
        });

        jLabel8.setText("Lista de Platos");

        jLabel9.setText("Platos por Menu");

        jLabel10.setText("Lista de Menus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAgregarMenu)
                .addGap(206, 206, 206))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(298, 298, 298)
                                        .addComponent(jButtonListarMenus))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(302, 302, 302)
                                        .addComponent(jButtonListarPlatos)
                                        .addGap(88, 88, 88))
                                    .addComponent(jScrollPane3))))
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarMenus)
                    .addComponent(jButtonListarPlatos)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAgregarMenu)
                .addGap(5, 5, 5)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLunesActionPerformed

    }//GEN-LAST:event_jRadioButtonLunesActionPerformed

    private void jRadioButtonMartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMartesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMartesActionPerformed

    private void jButtonAgregarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarMenuActionPerformed
        //Plato seleccionado par agregar
        rowSelPlato = jTableListaPlatos.getSelectedRow();
        Plato objAuxPlato = (Plato)ArrayPlatos.get(rowSelPlato);
        //Menu seleccionado para gregarlo
        rowSelMenu = jTableListaMenus.getSelectedRow();
        Menu objAuxMenu = (Menu)ArrayMenu.get(rowSelMenu);
//        objAuxMenu.listaPlatosMenu.add(objAuxPlato);
        //System.out.println(objAuxMenu);
         Collection nuevo = objAuxMenu.getPlatoCollection();
         nuevo.add(objAuxPlato);
         objAuxMenu.setPlatoCollection(nuevo);
        try {
            objLogMenu.edit(objAuxMenu);
            //System.out.println(ArrayMenu);
        } catch (Exception ex) {
            Logger.getLogger(AdministrarMenus.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        listarPlatosMenu(objAuxMenu.getPlatoCollection());
    }//GEN-LAST:event_jButtonAgregarMenuActionPerformed

    private void jButtonListarMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarMenusActionPerformed

        try {
            cargarMenus();
        } catch (IOException ex) {
            Logger.getLogger(AdministrarMenus.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdministrarMenus.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_jButtonListarMenusActionPerformed

    private void jButtonListarPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarPlatosActionPerformed

        try {
            cargarPlatos();
        } catch (IOException ex) {
            Logger.getLogger(RegistrarPlatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrarPlatos.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jButtonListarPlatosActionPerformed

    private void jButtonCrearMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearMenuActionPerformed
        String nombre = this.jTextFieldNombre.getText();
        String descripcion = this.jTextAreaDescripcion.getText();
        //Dias
        String dias = "";
        if (this.jRadioButtonLunes.isSelected()) {
            dias += "Lun|";
        }
        if (this.jRadioButtonMartes.isSelected()) {
            dias += "Mar|";
        }
        if (this.jRadioButtonMiercoles.isSelected()) {
            dias += "Mie|";
        }
        if (this.jRadioButtonJueves.isSelected()) {
            dias += "Jue|";
        }
        if (this.jRadioButtonViernes.isSelected()) {
            dias += "Vie|";
        }
        if (this.jRadioButtonSabado.isSelected()) {
            dias += "Sab|";
        }
        if (this.jRadioButtonDomingo.isSelected()) {
            dias += "Dom|";
        }
        //Meses
        String meses = "";
        if (this.jRadioButtonEnero.isSelected()) {
            meses += "Ene|";
        }
        if (this.jRadioButtonFebrero.isSelected()) {
            meses += "Feb|";
        }
        if (this.jRadioButtonMarzo.isSelected()) {
            meses += "Mar|";
        }
        if (this.jRadioButtonAbril.isSelected()) {
            meses += "Abr|";
        }
        if (this.jRadioButtonMayo.isSelected()) {
            meses += "May|";
        }
        if (this.jRadioButtonJunio.isSelected()) {
            meses += "Jun|";
        }
        if (this.jRadioButtonJulio.isSelected()) {
            meses += "Jul|";
        }
        if (this.jRadioButtonAgosto.isSelected()) {
            meses += "Ago|";
        }
        if (this.jRadioButtonSeptiembre.isSelected()) {
            meses += "Sep|";
        }
        if (this.jRadioButtonOctubre.isSelected()) {
            meses += "Oct|";
        }
        if (this.jRadioButtonNoviembre.isSelected()) {
            meses += "Nov|";
        }
        if (this.jRadioButtonDiciembre.isSelected()) {
            meses += "Dic|";
        }
        //Crear objeto Menu
        Menu objNuevoMenu = new Menu(null,nombre, descripcion, dias, meses);
        objLogMenu.create(objNuevoMenu);
            try {
                cargarMenus();
            } catch (IOException ex) {
                Logger.getLogger(AdministrarMenus.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdministrarMenus.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
    }//GEN-LAST:event_jButtonCrearMenuActionPerformed

    private void jTableListaMenusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaMenusMouseClicked
        rowSelMenu = this.jTableListaMenus.getSelectedRow();
        Menu aux = (Menu) ArrayMenu.get(rowSelMenu);
        Collection temp = aux.getPlatoCollection();
        listarPlatosMenu(temp);
        
    }//GEN-LAST:event_jTableListaMenusMouseClicked

    void listarPlatosMenu(Collection temp){
        this.jTablePlatosMenu.removeAll();
        Object columnas[] = {"Nombre", "Costo", "Descripcion", "Tiempo Aprox."};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTablePlatosMenu.setModel(modelo);
        for (Object Aux : temp) {
            Plato objAux = (Plato) Aux;
            String NewValor[] = {
                objAux.getNombre(),
                String.valueOf(objAux.getCosto()),
                objAux.getDescripcion(),
                String.valueOf(objAux.getTiempo())
            };
            modelo.addRow(NewValor);
        }
    }
    
    void cargarPlatos() throws IOException, FileNotFoundException, ClassNotFoundException {

        ArrayPlatos = objLogPlato.findPlatoEntities();
        this.jTableListaPlatos.removeAll();
        Object columnas[] = {"Nombre", "Costo", "Descripcion", "Tiempo Estimado(m)"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTableListaPlatos.setModel(modelo);
        for (Object objAux : ArrayPlatos) {
            Plato objPlato = (Plato) objAux;
            String NewValor[] = {
                objPlato.getNombre(),
                String.valueOf(objPlato.getCosto()),
                objPlato.getDescripcion(),
                String.valueOf(objPlato.getTiempo())
            };
            modelo.addRow(NewValor);
        }

    }

    void cargarMenus() throws IOException, FileNotFoundException, ClassNotFoundException {

        ArrayMenu = objLogMenu.findMenuEntities();
        this.jTableListaMenus.removeAll();
        Object columnas[] = {"Nombre", "Descripcion", "Dias", "Meses"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTableListaMenus.setModel(modelo);
        System.out.println(ArrayMenu);
        for (Object objAux : ArrayMenu) {
            Menu objMenu = (Menu) objAux;
            String NewValor[] = {
                objMenu.getNombre(),
                objMenu.getDescripcion(),
                objMenu.getDias(),
                objMenu.getMeses()
            };
            modelo.addRow(NewValor);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarMenu;
    private javax.swing.JButton jButtonCrearMenu;
    private javax.swing.JButton jButtonListarMenus;
    private javax.swing.JButton jButtonListarPlatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonAbril;
    private javax.swing.JRadioButton jRadioButtonAgosto;
    private javax.swing.JRadioButton jRadioButtonDiciembre;
    private javax.swing.JRadioButton jRadioButtonDomingo;
    private javax.swing.JRadioButton jRadioButtonEnero;
    private javax.swing.JRadioButton jRadioButtonFebrero;
    private javax.swing.JRadioButton jRadioButtonJueves;
    private javax.swing.JRadioButton jRadioButtonJulio;
    private javax.swing.JRadioButton jRadioButtonJunio;
    private javax.swing.JRadioButton jRadioButtonLunes;
    private javax.swing.JRadioButton jRadioButtonMartes;
    private javax.swing.JRadioButton jRadioButtonMarzo;
    private javax.swing.JRadioButton jRadioButtonMayo;
    private javax.swing.JRadioButton jRadioButtonMiercoles;
    private javax.swing.JRadioButton jRadioButtonNoviembre;
    private javax.swing.JRadioButton jRadioButtonOctubre;
    private javax.swing.JRadioButton jRadioButtonSabado;
    private javax.swing.JRadioButton jRadioButtonSeptiembre;
    private javax.swing.JRadioButton jRadioButtonViernes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableListaMenus;
    private javax.swing.JTable jTableListaPlatos;
    private javax.swing.JTable jTablePlatosMenu;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
