/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CLases.Pedido;
import CLases.Plato;
import CLases.PlatoPedido;
import static GUI.RegistrarPedido.objPedido;
import Logica.LogPedido;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Lopez
 */
public class AgregarPlato extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarPlato
     */
    static ArrayList<Pedido> ArrayPedidos = new ArrayList<>();
    static ArrayList<Plato> ArrayPlatos = new ArrayList<>();
    static ArrayList<PlatoPedido> ArrayPlatoPedidos = new ArrayList<>();

    static LogPedido objLogPedido = new LogPedido();

    int rowSel = -1;

    public AgregarPlato() throws IOException, FileNotFoundException, ClassNotFoundException {
        objLogPedido.LeerPedido(ArrayPedidos);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldBusquedaPedido = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedidoActual = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePlatosdisponibles = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTiempoApr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jButtonAgregarPlato2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaObservacion = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePedidoAdicionales = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jButtonAgregarPlato1 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel1.setText("Agregar Plato a Pedido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 230, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldBusquedaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBusquedaPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldBusquedaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 80, -1));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel2.setText("Platos del pedido");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jTablePedidoActual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePedidoActual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePedidoActualMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePedidoActual);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 150));

        jLabel3.setText("Numero de Pedido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 480, 300));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePlatosdisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablePlatosdisponibles);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 150));

        jLabel4.setText("Platos disponibles");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jTextFieldTiempoApr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTiempoAprActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldTiempoApr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 160, -1));

        jLabel5.setText("Cantidad:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 8, 1));
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jLabel10.setText("Plato por agregar");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jButtonAgregarPlato2.setText("Agregar Plato");
        jButtonAgregarPlato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarPlato2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAgregarPlato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jTextAreaObservacion.setColumns(20);
        jTextAreaObservacion.setRows(5);
        jScrollPane4.setViewportView(jTextAreaObservacion);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 330, -1));

        jLabel11.setText("Observacion:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 510, 620));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePedidoAdicionales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTablePedidoAdicionales);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 130));

        jLabel9.setText("Platos adicionales");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButtonAgregarPlato1.setText("Agregar adicionales");
        jButtonAgregarPlato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarPlato1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAgregarPlato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 480, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBusquedaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBusquedaPedidoActionPerformed

    private void jTextFieldTiempoAprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTiempoAprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTiempoAprActionPerformed

    private void jButtonAgregarPlato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarPlato1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarPlato1ActionPerformed

    private void jButtonAgregarPlato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarPlato2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarPlato2ActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        int busquedaPedido = Integer.parseInt(jTextFieldBusquedaPedido.getText());
        Pedido objNumeroPedido = new Pedido();
        objNumeroPedido.setNumeroPedido(busquedaPedido);
        LogPedido objLogPedidoAux = new LogPedido();

        Pedido objPedido = objLogPedidoAux.BuscarPedido(ArrayPedidos, objNumeroPedido);
        
        System.out.println("***");
        System.out.println(objPedido);
        
        jTablePedidoActual.removeAll();
        Object columnas[] = {"Nombre Plato", "Cantidad", "Observacion"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTablePedidoActual.setModel(modelo);
        
        if (objLogPedido.CompararPedido(objPedido, objNumeroPedido)) {

            for (PlatoPedido objPlatoPedido : objPedido.getListaPlatoPedido()) {
                PlatoPedido objPlatoPedidoAux = objPlatoPedido;
                String NewValor[] = {
                    objPlatoPedidoAux.getPlato().getNombre(),
                    String.valueOf(objPlatoPedidoAux.getCantidad()),
                    objPlatoPedidoAux.getObservacion()
                };
                System.out.println(objPlatoPedidoAux);
                modelo.addRow(NewValor);
            }

        }


    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTablePedidoActualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePedidoActualMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTablePedidoActualMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarPlato1;
    private javax.swing.JButton jButtonAgregarPlato2;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTablePedidoActual;
    private javax.swing.JTable jTablePedidoAdicionales;
    private javax.swing.JTable jTablePlatosdisponibles;
    private javax.swing.JTextArea jTextAreaObservacion;
    private javax.swing.JTextField jTextFieldBusquedaPedido;
    private javax.swing.JTextField jTextFieldTiempoApr;
    // End of variables declaration//GEN-END:variables
}
