/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CLases.Cliente;
import CLases.Factura;
import CLases.Pedido;
import CLases.Plato;
import CLases.PlatoPedido;
import static GUI.AgregarPlato.ArrayPedidos;
import static GUI.AgregarPlato.ArrayPlatos;
import static GUI.AgregarPlato.objLogPedido;
import static GUI.RegistrarPedido.objLogPedido;
import Logica.LogCliente;
import Logica.LogFactura;
import Logica.LogMenu;
import Logica.LogPedido;
import Logica.LogPlato;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author antse
 */
public class FacturaPantalla extends javax.swing.JInternalFrame {

    /**
     * Creates new form Factura
     */
    Pedido objNumeroPedido = new Pedido();
    static LogPedido objLogPedido = new LogPedido();
    static LogPlato objLogPlato = new LogPlato();
    static Pedido objPedido = new Pedido();
    static Pedido objPedidoAux = new Pedido();
    static LogMenu objLogMenu = new LogMenu();
    static LogFactura objLogFactura = new LogFactura();
    static LogCliente objLogCliente = new LogCliente();
    static Cliente objCliente = new Cliente();
    static Factura objFactura = new Factura();
    static ArrayList<Factura> ArrayFactura = new ArrayList<Factura>();
    static ArrayList<Cliente> ArrayCliente = new ArrayList<Cliente>();

    public FacturaPantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCalificacion = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedidos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDescripcionPedido = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNroPedido = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextTotalPagar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonCrearFactura = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldNroFactura = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jRadio1Estrella = new javax.swing.JRadioButton();
        jRadio3Estrella = new javax.swing.JRadioButton();
        jRadio5Estrella = new javax.swing.JRadioButton();
        jRadio4Estrella = new javax.swing.JRadioButton();
        jRadio2Estrella = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jButtonCrear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNombreApellido1 = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePedidos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 433, 103));

        jTableDescripcionPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableDescripcionPedido);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 433, 104));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("FACTURACION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jTextFieldNroPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNroPedidoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNroPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 114, -1));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel3.setText("Informacion factura");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        jLabel8.setText("Total a pagar:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jTextTotalPagar.setEnabled(false);
        getContentPane().add(jTextTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 186, -1));

        jLabel11.setText("Pedidos");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, 14));

        jLabel12.setText("Descripcion del pedido");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, 14));

        jButtonCrearFactura.setText("Crear Factura");
        jButtonCrearFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCrearFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 670, -1, -1));

        jLabel13.setText("Nro. Factura:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        jLabel14.setText("Fecha:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        jTextFieldNroFactura.setEnabled(false);
        getContentPane().add(jTextFieldNroFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 188, -1));

        jTextFieldFecha.setEnabled(false);
        getContentPane().add(jTextFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 188, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 358, -1));

        jLabel15.setText("Feedback:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel16.setText("Calificacion:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        buttonGroupCalificacion.add(jRadio1Estrella);
        jRadio1Estrella.setText("1 Estrellas");
        jRadio1Estrella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio1EstrellaActionPerformed(evt);
            }
        });
        jPanel1.add(jRadio1Estrella, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        buttonGroupCalificacion.add(jRadio3Estrella);
        jRadio3Estrella.setText("3 Estrellas");
        jPanel1.add(jRadio3Estrella, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        buttonGroupCalificacion.add(jRadio5Estrella);
        jRadio5Estrella.setText("5 Estrellas");
        jPanel1.add(jRadio5Estrella, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        buttonGroupCalificacion.add(jRadio4Estrella);
        jRadio4Estrella.setText("4 Estrelllas");
        jPanel1.add(jRadio4Estrella, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        buttonGroupCalificacion.add(jRadio2Estrella);
        jRadio2Estrella.setText("2 Estrellas");
        jPanel1.add(jRadio2Estrella, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 930, 140));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 188, -1));

        jLabel6.setText("Direccion:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel7.setText("Nombres ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 20));
        jPanel2.add(jTextFieldCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 188, -1));

        jLabel4.setText("Apellidos");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 20));
        jPanel2.add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 188, -1));

        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jLabel2.setText("C.I.:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));
        jPanel2.add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 188, -1));

        jLabel5.setText("Telefono/Celular:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel2.add(jTextFieldNombreApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 188, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 430, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadio1EstrellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio1EstrellaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio1EstrellaActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            // TODO add your handling code here:

            BuscarPedido();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(FacturaPantalla.class.getName()).log(Level.SEVERE, null, ex);
        }

        ArrayPedidos.removeAll(ArrayPedidos);
        try {
            objLogPedido.LeerPedido(ArrayPedidos);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(FacturaPantalla.class.getName()).log(Level.SEVERE, null, ex);
        }

        jTablePedidos.removeAll();
        Object columnas[] = {"Numero de Orden", "Numero de Mesa"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTablePedidos.setModel(modelo);

        if (objLogPedido.CompararPedido(objPedido, objNumeroPedido)) {

            String NewValor[] = {
                String.valueOf(objPedido.getNumeroPedido()),
                String.valueOf(objPedido.getNumeroMesa())
            };
            modelo.addRow(NewValor);

        }
        try {
            ListarPlatos();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(FacturaPantalla.class.getName()).log(Level.SEVERE, null, ex);
        }

        double totalPagar = objLogFactura.calcularTotalpagar(objPedido);

        this.jTextTotalPagar.setText(String.valueOf(totalPagar));
        try {
            GenerarNumeroFactura();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(FacturaPantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed
    public void GenerarNumeroFactura() throws IOException, FileNotFoundException, ClassNotFoundException {
        int numeroFactura;
        
        
        if (LogFactura.Existe()) {
            
                objLogFactura.LeerFactura(ArrayFactura);
            

            numeroFactura = ArrayFactura.get(ArrayFactura.size() - 1).getNumeroFactura() + 1;

        } else {
            numeroFactura = 1;
        }
        objFactura.setNumeroFactura(numeroFactura);
        this.jTextFieldNroFactura.setText(String.valueOf(numeroFactura));
        this.jTextFieldFecha.setText(String.valueOf(new Date()));
    }
    private void jTextFieldNroPedidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNroPedidoKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldNroPedidoKeyTyped

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        // TODO add your handling code here:
         
        objCliente = objLogCliente.CrearCliente(this.jTextFieldCI.getText(), this.jTextFieldNombreApellido1.getText(), this.jTextFieldApellido.getText(), this.jTextFieldDireccion.getText(), this.jTextFieldTelefono.getText());
        ArrayCliente.add(objCliente);
        
        try {
            objLogCliente.EscribirCliente(ArrayCliente);
        } catch (IOException ex) {
            Logger.getLogger(FacturaPantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonCrearFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearFacturaActionPerformed
        // TODO add your handling code here:
        String fechaParse = this.jTextFieldFecha.getText();
        SimpleDateFormat format = new SimpleDateFormat("EEE MMM d HH:mm:ss zzz yyyy");
        System.out.println(format);
        try {
            Date date = format.parse(fechaParse);
            objFactura = objLogFactura.CrearFactura(Integer.parseInt(this.jTextFieldNroFactura.getText()), date, Double.parseDouble(this.jTextTotalPagar.getText()), objCliente, objPedido);
            System.out.println("Factura");
            System.out.println(objFactura);
        } catch (ParseException ex) {
            Logger.getLogger(FacturaPantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_jButtonCrearFacturaActionPerformed
    public void BuscarPedido() throws IOException, FileNotFoundException, ClassNotFoundException {
        int busquedaPedido = Integer.parseInt(jTextFieldNroPedido.getText());
        objNumeroPedido.setNumeroPedido(busquedaPedido);
        ArrayPedidos.clear();
        objLogPedido.LeerPedido(ArrayPedidos);
        LogPedido objLogPedidoAux = new LogPedido();
        objPedido = objLogPedidoAux.BuscarPedido(ArrayPedidos, objNumeroPedido);
        System.out.println("/////");
        System.out.println(objPedido);
        objPedidoAux = objPedido;
        System.out.println("@@@@@@@");
        System.out.println(objPedidoAux);
    }

    public void ListarPlatos() throws IOException, FileNotFoundException, ClassNotFoundException {

        ArrayPlatos.removeAll(ArrayPlatos);
//        objLogPlato.LeerPlatos(ArrayPlatos);
//        ArrayPlatos = objLogMenu.MenuActivo().getListaPlatosMenu();

        jTableDescripcionPedido.removeAll();
        Object columnas[] = {"Nombre", "Descripcion", "Coste", "Cantidad"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTableDescripcionPedido.setModel(modelo);
        for (PlatoPedido objAux : objPedido.getListaPlatoPedido()) {

            String NewValor[] = {
                objAux.getPlato().getNombre(),
                objAux.getPlato().getDescripcion(),
                String.valueOf(objAux.getPlato().getCosto()),
                String.valueOf(objAux.getCantidad())
            };
            modelo.addRow(NewValor);
        }

    }

//    public void ListarPedidos() throws IOException, FileNotFoundException, ClassNotFoundException {
//
//        ArrayPedidos.removeAll(ArrayPedidos);
//        objLogPedido.LeerPedido(ArrayPedidos);
//        //ArrayPlatos = objLogMenu.MenuActivo().getListaPlatosMenu();
//
//        jTablePedidos.removeAll();
//        Object columnas[] = {"Numero de Orden", "Numero de Mesa"};
//        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
//        jTablePedidos.setModel(modelo);
//        for (Pedido objAux : ArrayPedidos) {
//            String NewValor[] = {
//                String.valueOf(objAux.getNumeroPedido()),
//                String.valueOf(objAux.getNumeroMesa())
//            };
//            modelo.addRow(NewValor);
//        }
//
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCalificacion;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonCrearFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadio1Estrella;
    private javax.swing.JRadioButton jRadio2Estrella;
    private javax.swing.JRadioButton jRadio3Estrella;
    private javax.swing.JRadioButton jRadio4Estrella;
    private javax.swing.JRadioButton jRadio5Estrella;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableDescripcionPedido;
    private javax.swing.JTable jTablePedidos;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCI;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldNombreApellido1;
    private javax.swing.JTextField jTextFieldNroFactura;
    private javax.swing.JTextField jTextFieldNroPedido;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextTotalPagar;
    // End of variables declaration//GEN-END:variables
}
