/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CLases.Menu;
import CLases.Mesero;
import CLases.Plato;
import Logica.LogMenu;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Lopez
 */
public class MeseroCargarMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form MeseroCargarMenu
     */
    Mesero mesero;

    ArrayList<Menu> ArrayMenu = new ArrayList<>();
    LogMenu objLogMenu = new LogMenu();
    Menu objMenu = new Menu();

    public MeseroCargarMenu( /*Mesero mesero*/) {
        //this.mesero = mesero;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMenu = new javax.swing.JTable();
        jButtonCargarMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(870, 400));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel1.setText("Cargar Menú del Día");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 230, 40));

        jTableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMenu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 420, 190));

        jButtonCargarMenu.setText("Cargar Menú");
        jButtonCargarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCargarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jLabel2.setText("Platos del Día:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCargarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarMenuActionPerformed
        // TODO add your handling code here:

        try {
            ArrayMenu.removeAll(ArrayMenu);
            objLogMenu.LeerMenu(ArrayMenu);
            objMenu = objLogMenu.MenuActivo();
            
            this.jTableMenu.removeAll();
            Object columnas[] = {"Nombre", "descripcion"};
            DefaultTableModel modelo = new DefaultTableModel(null, columnas);
            jTableMenu.setModel(modelo);
            for (Plato objAux : objMenu.getListaPlatosMenu()) {
                Plato objPlato = objAux;
                String NewValor[] = {
                    objPlato.getNombre(),
                    objPlato.getDescripcion(),               
                };
                modelo.addRow(NewValor);
            }
        } catch (IOException ex) {
            Logger.getLogger(MeseroCargarMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MeseroCargarMenu.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonCargarMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCargarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMenu;
    // End of variables declaration//GEN-END:variables
}
