/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CLases.Pedido;
import CLases.Plato;
import Logica.LogPedido;
import Logica.LogPlato;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Lopez
 */
public class RegistrarPedido extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrarPedido
     */
    ArrayList<Plato> ArrayPlatos = new ArrayList();
    LogPedido objLogPedido = new LogPedido();
    Pedido objPedido = new Pedido();

    public RegistrarPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombreMesero = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCodigoGeneral = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListaGeneral = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonBuscarNumero1 = new javax.swing.JButton();
        jButtonAgregarPlato1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButtonBuscar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextFieldTiempoApr1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaObservacion = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNumeroPedido3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePlatosPedido = new javax.swing.JTable();
        jButtonCrearPedido = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNumeroMesa = new javax.swing.JTextField();
        jTextFieldTiempoApr3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel1.setText("Registrar Pedido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 160, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Lista de Platos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jTextFieldNombreMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreMeseroActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombreMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 240, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 740, 10));

        jLabel4.setText("Codigo Pedido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        jTextFieldCodigoGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoGeneralActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCodigoGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 100, -1));

        jTableListaGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableListaGeneral);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 470, 150));

        jLabel5.setText("Nombre del Mesero:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setText("Cantidad:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jButtonBuscarNumero1.setText("Cargar");
        jButtonBuscarNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarNumero1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscarNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jButtonAgregarPlato1.setText("Agregar Plato");
        jButtonAgregarPlato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarPlato1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAgregarPlato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

        jLabel9.setText("Observacion:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, 20));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 8, 1));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        jButtonBuscar.setText("Buscar");
        jPanel1.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 180, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 140, -1));

        jTextFieldTiempoApr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTiempoApr1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTiempoApr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 160, -1));

        jLabel10.setText("Plato por agregar");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jTextAreaObservacion.setColumns(20);
        jTextAreaObservacion.setRows(5);
        jScrollPane4.setViewportView(jTextAreaObservacion);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 280, -1));

        jLabel7.setText("Numero de pedido:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jTextFieldNumeroPedido3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroPedido3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNumeroPedido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 800, 480));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Platos del Pedido");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTablePlatosPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTablePlatosPedido);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 470, 150));

        jButtonCrearPedido.setText("Crear Pedido");
        jButtonCrearPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearPedidoActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCrearPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        jLabel8.setText("Numero de Mesa:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jTextFieldNumeroMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroMesaActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldNumeroMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 170, -1));

        jTextFieldTiempoApr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTiempoApr3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldTiempoApr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 170, -1));

        jLabel11.setText("Tiempo Aproximado:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 120, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 510, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCrearPedidoActionPerformed

    private void jTextFieldNombreMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreMeseroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreMeseroActionPerformed

    private void jTextFieldCodigoGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoGeneralActionPerformed

    private void jButtonBuscarNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarNumero1ActionPerformed
        // TODO add your handling code here:
        System.out.println("...");
        System.out.println(ArrayPlatos);
        try {
            ArrayPlatos.removeAll(ArrayPlatos);

            LogPlato.LeerPlatos(ArrayPlatos);
        } catch (IOException ex) {
            Logger.getLogger(RegistrarPedido.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrarPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTableListaGeneral.removeAll();
        Object columnas[] = {"Nombre","Costo","Descripcion","tiempo"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTableListaGeneral.setModel(modelo);
        for(Plato objAux:ArrayPlatos){
            Plato objPlato = objAux;
            String NewValor[]={
                objPlato.getNombre(),
                objPlato.getDescripcion(),
                String.valueOf(objPlato.getCosto()),
                String.valueOf(objPlato.getTiempo())
            };
            modelo.addRow(NewValor);
            
        }
    }//GEN-LAST:event_jButtonBuscarNumero1ActionPerformed

    private void jButtonAgregarPlato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarPlato1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarPlato1ActionPerformed

    private void jTextFieldNumeroMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroMesaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextFieldTiempoApr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTiempoApr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTiempoApr1ActionPerformed

    private void jTextFieldTiempoApr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTiempoApr3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTiempoApr3ActionPerformed

    private void jTextFieldNumeroPedido3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroPedido3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroPedido3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarPlato1;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonBuscarNumero1;
    private javax.swing.JButton jButtonCrearPedido;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTableListaGeneral;
    private javax.swing.JTable jTablePlatosPedido;
    private javax.swing.JTextArea jTextAreaObservacion;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCodigoGeneral;
    private javax.swing.JTextField jTextFieldNombreMesero;
    private javax.swing.JTextField jTextFieldNumeroMesa;
    private javax.swing.JTextField jTextFieldNumeroPedido3;
    private javax.swing.JTextField jTextFieldTiempoApr1;
    private javax.swing.JTextField jTextFieldTiempoApr3;
    // End of variables declaration//GEN-END:variables
}
