package CLases;

//

import java.io.Serializable;
import java.util.ArrayList;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UMA
//  @ File Name : colaPedido.java
//  @ Date : 14/5/2020
//  @ Author : UMA_TEAM
//
//




public class colaPedido implements Serializable{
	public ArrayList<Pedido> listaPedidos = new ArrayList<Pedido>();

    public colaPedido() {
    }
        
	public void agregarPedido(Pedido pedido) {
            this.listaPedidos.add(pedido);
	}
	
	public void eliminarPedido(Pedido pedido) {
            this.listaPedidos.remove(pedido);
	}
}
