package CLases;

//
import java.io.Serializable;
import java.util.Date;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UMA
//  @ File Name : Factura.java
//  @ Date : 14/5/2020
//  @ Author : UMA_TEAM
//
//
public class Factura implements Serializable {

    public int numeroFactura;
    public Date fechaFactura;
    public double valor;
    public Cliente cliente;
    public Pedido pedido;
    public FeedBack feedBack;

    public Factura() {
    }

    public Factura(int numeroFactura,Date fechaFactura,double valor, Cliente cliente, Pedido pedido) {
        this.numeroFactura = numeroFactura;
        this.fechaFactura = fechaFactura;
        this.valor = valor;
        this.cliente = cliente;
        this.pedido = pedido;
    }

    public Factura(int numeroFactura,Date fechaFactura,double valor, Cliente cliente, Pedido pedido, String calificacion, String observacion) {
        this.fechaFactura = fechaFactura;
        this.numeroFactura = numeroFactura;
        this.valor = valor;
        this.cliente = cliente;
        this.pedido = pedido;
        this.feedBack = new FeedBack(calificacion, observacion);
    }

    public void agregarFeedback(String calificacion, String observacion) {
        this.feedBack = new FeedBack(calificacion, observacion);
    }

    public double getValor() {
        return valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Pedido getPedido() {
        return pedido;
    }

    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }

    public FeedBack getFeedBack() {
        return feedBack;
    }

    public void setFeedBack(FeedBack feedBack) {
        this.feedBack = feedBack;
    }

    public int getNumeroFactura() {
        return numeroFactura;
    }

    public void setNumeroFactura(int numeroFactura) {
        this.numeroFactura = numeroFactura;
    }

    public Date getFechaFactura() {
        return fechaFactura;
    }

    public void setFechaFactura(Date fechaFactura) {
        this.fechaFactura = fechaFactura;
    }

    @Override
    public String toString() {
        return "Factura{" + "numeroFactura=" + numeroFactura + ", fechaFactura=" + fechaFactura + ", valor=" + valor + ", cliente=" + cliente + ", pedido=" + pedido + ", feedBack=" + feedBack + '}';
    }

    

}
