package CLases;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UMA
//  @ File Name : PlatoPedido.java
//  @ Date : 14/5/2020
//  @ Author : UMA_TEAM
//
//




public class PlatoPedido {
	public int estado;
	public Plato plato;

    public PlatoPedido() {
    }

    public PlatoPedido(int estado, Plato plato) {
        this.estado = estado;
        this.plato = plato;
    }

    public int getEstado() {
        return estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    public Plato getPlato() {
        return plato;
    }

    public void setPlato(Plato plato) {
        this.plato = plato;
    }

    @Override
    public String toString() {
        return "PlatoPedido{" + "estado=" + estado + ", plato=" + plato + '}';
    }
        
}
