package CLases;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UMA
//  @ File Name : PlatoPedido.java
//  @ Date : 14/5/2020
//  @ Author : UMA_TEAM
//
//
public class PlatoPedido {

    public int cantidad;
    public int estado;
    public String observacion;
    public Plato plato;

    public String getObservacion() {
        return observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public PlatoPedido() {
    }

    public PlatoPedido(int estado) {
        this.estado = estado;
    }

    public PlatoPedido(int cantidad, int estado, String observacion, Plato plato) {
        this.cantidad = cantidad;
        this.estado = estado;
        this.observacion = observacion;
        this.plato = plato;
    }

    public PlatoPedido(int cantidad, int estado, Plato plato) {
        this.cantidad = cantidad;
        this.estado = estado;
        this.plato = plato;
    }

    public int getCantidad() {
        return cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public int getEstado() {
        return estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    public Plato getPlato() {
        return plato;
    }

    public void setPlato(Plato plato) {
        this.plato = plato;
    }

    @Override
    public String toString() {
        return "PlatoPedido{" + "cantidad=" + cantidad + ", estado=" + estado + ", plato=" + plato + '}';
    }
  

}
